roxypoceros/CDMX012-social-network

- src/componets/Home.js
- src/componets/Register.js
- src/index.html
- src/main.js
Ya quedo @roxypoceros @roxanaggr
> Primer boton

- src/componets/Login.js
- src/main.js
Hola, estos ya son los cambios al dom sin errores. @lourdessantiago @roxypoceros
> modificaciones al dom 

- src/componets/Register.js
- src/firebase.js
Ya casi está listo el módulo para la autenticación
> modularizacion firebase

- src/componets/Feed.js
- src/componets/Login.js
- src/componets/Register.js
- src/firebase.js
- src/main.js
> se hizo el boton de cerrar sesion y comenzamos con el feed

- src/componets/Feed.js
- src/componets/Publish.js
- src/firebase.js
- src/main.js
- src/style.css
Hola, se está trabajando en los datos que se van a guardar en la database de firestore pero aún no funciona @lourdessantiago @roxypoceros
> esqueleto para pagina de post nuevo

- src/componets/Publish.js
- src/firebase.js
Se agregó la función para crear posts, tendremos que editar el objeto de la función
> funcion para agregar posts a firestore

- src/componets/Feed.js
- src/componets/Login.js
- src/componets/Register.js
- src/firebase.js
- src/main.js
> se vinculo la pagina de feed al momento de logearse y registrarse

- src/componets/Feed.js
- src/componets/Register.js
- src/firebase.js
- src/index.html
- src/style.css
> obtuvimos la data de firestore para verla en la pagina de feed

- src/index.js
> seccion de post y feed en una sola pagina

- src/componets/Login.js
- src/componets/Register.js
- src/index.html
- src/style.css
@roxanaggr @roxypoceros  aquí les dejo los cambios, ya aparecen las alertas de los diferentes errores en el registro y en el login .
> Alertas en el login y en register

- src/componets/Feed.js
- src/firebase.js
> el boton de publicar ya imprime en pantalla los ultimos posts

- src/componets/Feed.js
- src/firebase.js
- src/style.css
> boton para borrar en cada post

- src/componets/Feed.js
- src/firebase.js
- src/style.css
> funcion borrar posts y editar

- src/componets/Feed.js
- src/componets/Home.js
- src/componets/Login.js
- src/componets/Register.js
- src/style.css
Se agrega imagen para desktop y mas oscura para cel, estilos de botón es por clase y estilos para las alertas de errores
@roxanaggr @lourdessantiago
> Cambios en estilos

- src/componets/Feed.js
- src/componets/Home.js
- src/componets/Login.js
- src/componets/Register.js
- src/style.css
> Newstyles con los cambios que se hicieron en la mañana

- src/componets/Login.js
Hola querida @PerlaDelAngel  esperamos nos puedas ayudar con el code review. Saludos @roxypoceros @roxanaggr
> quitamos unas lineas que no servian

- src/componets/Feed.js
> Mensaje de cerrar sesión listo

- src/componets/Feed.js
- src/componets/Home.js
- src/componets/Register.js
- src/firebase.js
Hola ya se muestra el nombre y foto de google al loguearse con gmail @lourdessantiago @roxypoceros
> Imagen y nombre del usuario con gmail

- src/style.css
> Estilos para desktop

- src/componets/Feed.js
- src/firebase.js
El código aún tiene que modularizarse @lourdessantiago @roxypoceros
> Función editar y borrar según usuario lista

- src/componets/Feed.js
- src/firebase.js
Hola. Ya se puede editar el post. El único problema que falta por solucionar es que al hacer clic en el botón de editar otro post, hay un error con un removeChild @lourdessantiago @roxypoceros
> el post ya se puede editar sin duplicarse

- src/componets/Feed.js
- src/componets/Register.js
> Alerta primer publicación y publicación en blanco

- src/componets/Feed.js
- src/firebase.js
> primeras pruebas

- src/componets/Feed.js
- src/firebase.js
- src/style.css
Ya esta el conteo de likes con el botón @roxypoceros @roxanaggr
> Likes y conteo

- src/componets/Feed.js
Aquí podemos visualizar los likes, los dislikes y el contador funcionando de forma correcto. @roxypoceros @roxypoceros
> Funcion like, dislike y contador que ya funcionan

- src/componets/Feed.js
Ya sirve el contador de likes y dislikes @roxypoceros @roxypoceros
> Se resolvió el error del contador de likes

- src/componets/Feed.js
- src/componets/Publish.js
- src/firebase.js
- src/style.css
Hola. Ya terminamos!! @lourdessantiago @roxypoceros
> estilos y comentarios finales
